#config
---
property:
  name: ${user.dir}/@project.artifactId@-@project.version@.@packaging@
  api:
    end-point: /api
  jwt:
    key: ENC(OSpYSdJtNoXeebM36n2vI11cBS9ZKO8cG56ndGc0YvolyW6ECf11MuwETS4nbZ2R5emSBn6gbI0aItGCiTfusw==)
# default
logging:
  config: classpath:config/logback/logback.xml
spring:
  messages:
    always-use-message-format: false
    encoding: UTF-8
    basename: config/message/messages
  datasource:
    schema: classpath:/config/sql/role.sql
    initialization-mode: always

# default(local)
---
server:
  port: 8010
spring:
  banner:
    location: classpath:config/banner/default
  h2:
    console:
      enabled: false
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: ENC(CasVWKjJ/V5YPQxxhbEnZ14ah5PW7Mmy8sa8L+p5pFbt/DkgQB42Z9fxwp383HH1TXyLEEpJfh2wj6r51GK3BwFSCM3/mZ5Q8XJmSWB/znY=)
    username: sa
    password:
# dev
---
server:
  port: 80
spring:
  profiles : dev
  banner:
    location: classpath:config/banner/dev
# prod
---
server:
  port: 80
spring:
  profiles : prod
  banner:
    location: classpath:config/banner/prod